### Manipulacao de Dados com Numpy

#### Aula 4 – Estruturas de Dados NumPy !

In [1]:
# Primeiro veja a versao do Python que estamos utilizando
# O sinal ! antes do comando indica que vamos executar um comando no SO, neste caso vamos ver a versao do Python instalada
!python -V

Python 3.9.12


In [2]:
# Caso voce queira atualizar algum pacote basta executar o comando abaixo
# !pip install -U nome_do_pacote

# Caso você queira instalar uma versão especifica de algum pacote, então execute o comando abaixo
# !pip install nomepacote==versao


# Sempre apos instalar ou atualizar um pacote, reinicie o Jupyter notebook para garantir o devido funcionamento

##### Uma das principais funcionalidades com NumPy e voce carregar dados atraves de uma estrutura NumPy que e a forma que os dados sao colocados na memoria.

##### Os dados podem se originar de um arquivo CSV, um banco de dados, entre outros locais, precisamos trazer estes dados para o Python para voce trabalhar e o NumPy oferece estrutura de dados para esta tarefa.

In [3]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [4]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 4 Parte 1

### Estrutura NumPy -  Array

In [5]:
# Vamos comecar criando nosso primeiro Array Numpy e imprimir ele para vermos
# O ideal e sempre vc separar cada comando para em caso de erros vc conseguir facilmente identifica-los
# E tambem vc consegue processar os scripts por pedacoes o que ajuda a deixar mais performatico
# Porem caso queira vc pode utilizar o ; para executar mais de um comando seguido ou escrever o codigo embaixo sem o ;
array1 = np.array([1,2,3,4])
print(array1)

# Essa Funcao sera muito utilizada, nos chamamos o pacote numpy passamos que queremos um array
# Dentro do parenteses nos passamos uma lista [] com os numeros separados por virgula e entao imprimimos com print na tela

[1 2 3 4]


In [6]:
# Agora vamos verificar o formato do array (chamamos normalmente de shape)
# o shape e uma descricao do objeto, neste caso o array que criamos
array1.shape

# Veja, ele nos disse que é um vetor de 4 elementos e apenas 1 dimensao, o vazio depois da virgula mostra que temos uma unica
# dimensao ou seja uma unica "coluna e 4 linhas"

(4,)

In [7]:
# Vamos confirmar agora verificando o numero de dimensoes deste array
# Veja que tem apenas 1 dimensao
array1.ndim

1

In [8]:
# Agora vamos criar um array de duas dimensoes
array2 = np.array([[1,2,3],[4,5,6]]);print(array2)

# Perceba que desta vez nos estamos passando 2 listas dentro de outra lista
# Ou seja chamamos isto de lista de listas em python e a forma de criar arrays com mais de 1 dimensao
# Este array sao 2 dimensoes com 3 registros cada dimensao

[[1 2 3]
 [4 5 6]]


In [9]:
# Shape
array2.shape

# Veja temos 2 dimensoes com 3 registros cada dimensão.

(2, 3)

In [18]:
array2[0,2]

3

In [10]:
# Numero de dimensoes
array2.ndim

2

##### Nao esqueca que em Python tudo e objeto
##### Vamos ver exemplos de Metodo e atributos de um objeto

In [9]:
# Metodo
# Vamos usar o metodo MAX para ver o valor maximo do nosso objeto array2
array2.max()

# Veja o numero 6 e o maior valor

6

In [10]:
# Atributo
array2.ndim

# Perceba que nosso objeto array2 tem duas dimensoes como atributo

2

#### Dica
##### Nunca tente decorar metodos e atributos, sao milhares ou ate mais.
##### Sempre que vc se deparar com um problema ou objetivo, se pergunte, sera que existe um metodo ou atributo para este problema
##### Muito provavelmente existira, pois o python e uma linguagem conforme falamos antes muito vem desenvolvida por uma enorme comunidade
##### Por isso sempre trabalhe com a documentacao do pacote que voce esta utilizando, nunca se esqueca disso

### Aula 4 Parte 2

### Criando uma Estrutura NumPy com funcao Arange

In [15]:
# Essa funcao permite nos criamos um array conforme precisamos 
# Veja este exemplo, queremos um array com registros de 0 a 14
# Sempre lembre que python e a começa do 0 por isso ele foi do 0 ao 14 totalizando 15 registros
array3 = np.arange(15)

In [16]:
# Veja o array
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
# Nos podemos passar mais parametros para criacao do array e deixa-lo customizado
# Neste caso passamos o inicio, fim e os "pulos" que queremos
# O ultimo numero nesta funcao e ignorado ou seja vc teria que passar ate o 16 para ele retornar o 15
array4 = np.arange(0,16,3);print(array4)

# Neste caso pedimos um array do 0 ao 14 pulando de 3 em 3
# Veja que no caso ele nao trouxe o ultimo numero pois nao tem casas o suficiente para ele ter ido ate o 15 que seria o proximo

[ 0  3  6  9 12 15]


### Aula 4 Parte 3

### Criando uma Estrutura NumPy com funcao Linspace

In [19]:
# Esta funcao vai criar o array com o intervalo entre os numero igual ou seja linear
# Veja nos passamos o valor de inicio, fim e o numero de elementos que queremos
array5 = np.linspace(0,10,5) ; array5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Outras funcoes para criar estruturas

#### numpy.zeros

In [20]:
# Vamos criar um array preenchido com zeros
# chamamos a funcao e passamos o numero de registros que queremos e o numero de dimensoes
# No caso sao 10 linhas e 8 colunas
# Os . e pq os valores foram criados do tipo float/decimal
array6 = np.zeros((10,8)) ; array6

# Um exemplo do uso deste tipo de array e quando estamos treinamdo um modelo de rede neural artificial
# Todo o treinamento dessa rede neural e feito atravez de operacoes com arrays
# Usamos este tipo de array para criar os pesos, entao damos a estrutura para o array com zero
# E os valores vao mudando conforme o andamento do processo, e uma forma de organizacao do trabalho

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### numpy.ones

In [21]:
# Ou entao podemos criar um array preenchido com valores 1
# Neste caso pedimos para criar 2 arrays com 4 registros e 3 colunas
array7 = np.ones((2,4,3)) ; array7

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### numpy.eye

In [22]:
# Podemos criar uma matriz identidade
array8 = np.eye(4) ; array8

# E uma matriz preenchida com 0 e numeros 1 na diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### numpy.diag

In [24]:
# Podemos criar uma matriz diagonal, so que desta vez informando os numeros que queremos na diagonal
array9 = np.diag((1,2,3,4,5,6,7))
array9

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

#### numpy.random.rand

In [25]:
# Esta funcao cria uma sequencia de numeros uniformemente distribuidos com range de 0 até onde vc escolher
array10 = np.random.rand(10); array10

array([0.8298857 , 0.56189802, 0.97275979, 0.28636579, 0.6154736 ,
       0.08587671, 0.23576666, 0.38814478, 0.69325312, 0.91826022])

#### np.random.randn

In [26]:
# Esta funcao é muito boa, ela cria uma sequencia de numeros com distribuicao normal
# A distribuicao normal e um tipo de distribuicao muito utilizada na estatistica
array11 = np.random.randn(10); array11

array([ 0.7981207 ,  0.02705702,  1.11642667,  0.65727063,  2.99324829,
        0.30515055,  1.79800338, -0.17052628, -1.28495349,  0.17709576])

#### numpy.empty

In [21]:
# Podemos tambem criar um array vazio
# Neste caso queremos 3 registros e 2 dimensoes
# Este e o mesmo caso do array preenchido com 0 onde vc quer apenas a estrutura e depois a preenche
# Esses numeros sao apenas lixo de memoria, ele esta vazio mesmo
array12 = np.empty((3,2)) ; array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### numpy.tile

In [28]:
# Neste caso vamos replicar os valores de um array
# Veja exemplo vamos começar criando um array normal
array13 = np.array([[1,2,3], [4,5,6]]);array13

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Veja que estamos replicando o array
# Repetindo 4 vezes os registros do array
array14 = np.tile(np.array([[1,2], [4,5]]), 4); print(array14)

[[1 2 1 2 1 2 1 2]
 [4 5 4 5 4 5 4 5]]


In [30]:
# Podemos replicar tbm o numero de dimensoes alem do numero de registros
array15 = np.tile(np.array([[1,2], [4,5]]), (2,2)); print(array15)

[[1 2 1 2]
 [4 5 4 5]
 [1 2 1 2]
 [4 5 4 5]]
