### Manipulacao de Dados com Numpy

#### Aula 9 – Array Multidimensional!

In [2]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [3]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 9 – Array Multidimensional!

In [4]:
# Vamos criar um array com shape 3,3
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]]);array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Vamos retornar os elementos da terceira linha da matriz
# Veja que o resultado é exatamente a ultima linha do 
# A linha de indice 2

array1[2]

array([7, 8, 9])

In [6]:
# Vamos retornar os elementos da terceira linha da matriz de outra forma
# Veja que o resultado é exatamente a ultima linha do 
# A linha de indice 2

array1[2,]

array([7, 8, 9])

In [7]:
# Retornando todas as linhas da segunda coluna da matriz
# Perceba que queremos todas as linhas, e apenas a coluna de indice 1
# Perceba que nos selecionamos uma coluna porem,
# Ele retorna uma unica lista de valores
# Basta ver como os dados sao retornados

array1[:,1]

array([2, 5, 8])

In [8]:
# Fatiamento/Slicing da matriz
# Aqui queremos a linha de indice 2 e 
# a coluna de indice 1

array1[2,1]

8

In [9]:
# Agora vamos usar atribuicao
# Vamos mudar um dos elementos da matriz 
# Vamos mudar o elemento da linha de indice 1 e coluna indice 2


# Nos chamamos o array e 
# indicamos atravez do slicing o elemento que queremos atribuir o novo valor
# Perceba que o elemento foi alterado

array1[1,2] = 16 ; array1

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [11]:
# Vamos criar mais um array para fazer um teste
# Temos um array de 3 elementos

array2 = np.array([10,11,12])
array2.shape

(3,)

In [12]:
# Claro
# Veja que ao chamar um elemento que nao existe no array
# Retorna um erro
array2[6]

IndexError: index 6 is out of bounds for axis 0 with size 3

##### Se atente a mensagem IndexError, pois vc pode receber esta mensagem muitas vezes trabalhando com dados, varias situacoes vc pode transformar os dados e acabar recebendo esta mensagem. Essa mensagem significa que esta ocorrendo um erro no slicing, filtragem dos dados