### Manipulacao de Dados com Numpy

#### Aula 11 – Transposicao e Reshaping de Arrays

In [1]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [2]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


###  Aula 11 – Transposicao e Reshaping de Arrays

#### Esta aula e muito importante, pois um dos trabalhos que mais podem dar trabalho e voce mudar o formato dos dados para mudar a forma de calcular ou adequar o formato para alguma view ou algoritmo que precisa receber os dados em um formato diferente do original, e com numpy podemos fazer isto facilmente.

#### Vamos mais uma vez aumentar o grau de dificuldade

### Transposicao e Reshaping de Arrays

In [3]:
# Vamos comecar criando um array normal
# Eu gosto de trabalho com um array menor,
# Para vc conseguir acompanhar as alteracoes sendo feitas facilmente

array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
# Vamos ver o shape do array original
array1.shape

(2, 5)

In [5]:
# Vamos fazer a transposta da matriz (tbm conhecido como pivot)
# Perceba que os dados mudaram de formato
# O shape foi invertido
# O que era linha virou coluna e o que era coluna virou linha
array1.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [6]:
# Veja o shape invertido
# o T e um metodo indicando que queremos a transposta
array1.T.shape

(5, 2)

In [7]:
# Vamos fazer a transposta da matriz(pivot) com funcao np

np.transpose(array1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [8]:
# Veja o shape
np.transpose(array1).shape

(5, 2)

##### Saiba que fazer a transposta e uma tarefa fundamental para criacao de modelos de inteligencia artifical avancados, IA em muitos casos e matematica pura e usa operacoes entre matrizes.

### Broadcasting

#### Broadcasting e outro conceito ligado a transposicao de matrizes, que e a forma como o numpy trata arrays de diferentes formas durante operacoes entre esses arrays.


In [9]:
# Vamos começar criando 2 arrays com diferentes shapes
# Sendo o primeiro array de 3 dimensoes com 1 registro cada dimensao
array1 = np.array([[1], [2], [3]])
array1


array([[1],
       [2],
       [3]])

In [10]:
array1.shape

(3, 1)

In [11]:
# O segundo array tem uma unica dimensao com 3 registros
array2 = np.array([4, 5, 6])
array2

array([4, 5, 6])

In [12]:
# Perceba que os 2 arrays tem formatos diferentes
array2.shape

(3,)

In [13]:
# Entao nos vamos aplicar um broadcast entre os arrays de diferentes formatos
np.broadcast(array2, array1)

In [14]:
array1 = np.array([[1], [2], [3]])
array2 = np.array([4, 5, 6])



In [15]:
operacao = np.broadcast(array1, array2)
operacao

In [16]:
# Perceba que vai dar um erro pois ainda  nao temos um objeto array que possamos fazer slicing deste broadcast
operacao.shape

(3, 3)

In [17]:
# Perceba que o slicing nao funcionou
# pois os dados estao no formato np.broadcast e nao array que da para fazer slicing
# Este objeto possui um shape e pode ser usado para aplicar loops mas nao podemos fazer slicing ainda
operacao[:]

TypeError: 'numpy.broadcast' object is not subscriptable

In [ ]:
# Veja que vou usar outro recurso de bradcast do numpy
# Ele conseguiu vamos dizer compatibilizar os 2 arrays de diferentes formas
# 1 array tinha 3 dimensoes e 1 registro cada o outro era o aposto
# Entao ele gerou um array de 3,3 para cada array
# Vamos fazer uma operacao entre esses 2 arrays
# perceba que os arrays foram esticados para conseguir serem compativeis
np.broadcast_arrays(array1, array2)

In [18]:
# Olha que legal o que vamos fazer 
# Vamos criar um array vazio que vai receber a operacao gerando assim um array com o broadcast
# Sendo que o formato deste array vai ser o shape do broadcast 

saida = np.empty(operacao.shape)
saida

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.33982810e-321],
       [1.24610723e-306, 1.29061142e-306, 7.34514117e+223]])

In [19]:
# Agora vamos fazer uma iteracao entre os arrays do bradcast aplicando uma operacao
# Usando este lint comprehension conseguimos aproveitar alguns recursos a mais
# Veja que a saida e uma iteracao entre os arrays
# Array 1 era [1] [2] [3]
# array2 [4 5 6]
# Entao ele gerou uma saida que fosse [4+1,5+1,6+1], [4+2,5+2,6+2], [4+3,5+3,6+3]
saida.flat = [u*v for (u,v) in operacao]
saida


array([[ 4.,  5.,  6.],
       [ 8., 10., 12.],
       [12., 15., 18.]])

In [20]:
saida[0]

array([4., 5., 6.])

### Broadcasting com Transposicao de matrizes

#### Nos vamos aplicar desta vez os dois conceitos que aprendemos nesta aula juntos aplicacando o Broadcast entre matrizes de diferentes formatos

In [21]:
array3 = np.array([[1,2,3]]);array3

array([[1, 2, 3]])

In [22]:
# Transposta do array
array3.T

array([[1],
       [2],
       [3]])

In [23]:
# Agora vamos fazer uma operacao
# Entre o array2 e a sua transposta
array3.T + array3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [27]:
# Perceba o que aconteceu, o array2 normal tem 1 linha e 3 colunas
array3

array([[1, 2, 3]])

In [28]:
# Ja o array2 com transposta tem 3 linhas e 1 coluna
array3.T

array([[1],
       [2],
       [3]])

In [26]:
# O que aconteceu
# O Numpy pegou os 3 elementos do array3 origina e sou cada elemento 
# Pelo elemento do array3 transposta
# 1+1,2+1,3+1 depois 1+2,2+2,3+2 depois 1+3, 2+3, 3+3
# No final ficou um array 3 por 3
array3.T + array3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
# O que acontece se em vez de fazer a operacao com array,
# Nos fazermos a operacao com o shape do array 
# Ficou em dificil de entender, nao ?
# Calma que eu explico
array3.T + array3.shape

array([[2, 4],
       [3, 5],
       [4, 6]])

In [32]:
array3.T

array([[1],
       [2],
       [3]])

In [33]:
array3.shape

(1, 3)

In [30]:
# O shape do array2 e == 1, 3 ou seja 2 registros 1 dimensao
# O array2 original e == 1,2,3
# Ele fez o mesmo raciocinio 
# Pegou o 1º elemento do array2 original o 1 e somou por cada elemento do shape do array2
# Ou seja 
# 1+1 = 2, 1+3 = 4 depois
# 2+1 = 3, 2+3 = 5 depois
# 3+1 = 4, 3+3 = 6
array3.T + array3.shape

# Ae que entra o conceito que eu falei que dependendo da forma que vc fazer o slicing
# Pode mudar o resultado da operacao usando shape

array([[2, 4],
       [3, 5],
       [4, 6]])