### Manipulacao de Dados com Numpy

#### Aula 12 – Transformando Matrizes em Vetores

In [3]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [4]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 12 – Transformando Matrizes em Vetores

##### Uma tarefa muito comum em machine learning e transformarmos matrizes em vetores, isso muda o formato dos dados

In [5]:
# Vamos criar um array comum mas dessa vez
# Vamos usar o arange para cada dimensao do array
# Ou seja um array de arrays = uma matriz de 2 arrays de 5 registros

array3 = np.array([np.arange(0,5),np.arange(5,10)])
array3

# Perceba que nao precisamos usar uma lista de listas
# Pois a funcao arange ja cria um array("uma lista")

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
# Neste caso sao 2 dimensoes(2 arrays) com 5 registros
# Perceba que apesar de ser 2 linhas e 5 colunas
# Mas quando vermos as dimensoes sera apenas 2 dimensoes pois e isso que e mesmo
# Isso pode confundir mas e pq segue o mesmo raciocinio do slicing
# Dependendo da maneira que nos criamos a matriz as saidas podem variar tambem
# Isso e muito comum em programacao, pois sao muitas possibilidades de apliacao das funcoes, nao se assuste

array3.shape

(2, 5)

##### Em alguns modelos de machine learning nao da para trabalhar com a matriz em si, isso dificulta o processamento na hora de realizar o treinamento do modelo, por isso em varios momentos precisamos transformar a matriz em um vetor. Ou seja, aplicamos todas as transformacoes necessarias e antes de treinar o modelo convertemos a matriz em um vetor.

In [7]:
# Para isso usamos a funcao ravel
# Veja ele pegou as 2 dimensoes e colocou em apenas uma
# Visao computacional que e uma forma de IA usa este conceito
# De transformar uma matriz em vetor
# Pois a imagem e uma matriz e para treinar o modelo precisamos passa-la para vetor

array3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Aplicando a transposta antes do ravel veja que o resultado muda completamente

array3.T.ravel()

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [13]:
# Pois ele foi colocando em blocos, como se uma linha fosse ficando na frente da outra
# 0-5,1-6,2-7, etc, pois de 2 dimensoes ele virou objeto de 5 dimensoes
array3.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])