### Manipulacao de Dados com Numpy

#### Aula 5 – Tipos de Dados NumPy !

In [4]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [5]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 5 - Tipos de Dados NumPy

##### Ate o momento nos apenas aplicamos funcoes e o proprio numpy definiu o tipo de dados, porem normalmente no nosso dia a dia, nos queremos nos mesmos definir o tipo de dados que queremos, e isso que vamos estar estudando agora nesta aula, tipos de dados numpy

In [6]:
# Vamos desta vez criar os arrays e passando para a funcao o argumento de que tipo de dados queremos
array2 = np.array([1,2,3,4,5], dtype ='float')
array3 = np.arange(-10,10,1, dtype = 'float')

In [8]:
print(array3)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.]


In [10]:
# Vamos verificar o tipo de dados
# O padrao e float64 mas temos tbm o float32, o que muda e o padrao das casas decimais
array2.dtype

dtype('float64')

In [11]:
# Agora vamos cria rum array sem passar o tipo do dado que queremos
# Repare que ao imprimir na tela nao temos os pontos depois dos numeros 
array4 = np.array([3,6,9,12]);array4

array([ 3,  6,  9, 12])

In [12]:
# Verificando o tipo
array4.dtype

dtype('int32')

In [14]:
# Agora veja se recriarmos o mesmo array so que desta vez
# Vamos incluir casa decimal em um dos numeros, apenas 1 numero
# E vamos deixar o numpy definir sozinho o tipo de numero
array5 = np.array([3.0,6,9,12]);array5

array([ 3.,  6.,  9., 12.])

In [15]:
# E importanto nos fazermos este exercicio em todos os pacotes que voces usarem
# Isso para cada tipo de dado vc tem diferentes operacoes que podem ser aplicadas
# E muito comum vc querer controlar o tipo de dado que vc quer que seja gerado para efeito de precisao
# A ferramenta nao sabe o que vc quer, por isso e importante vc ter o controle disto
# Veja o Numpy fez o esperado, ele viu um numero decimal e por isso nao considerou int
# Caso contrario ele teria perdido precisao usando numeros inteiros, ele nao fez isso

array5.dtype

dtype('float64')

In [17]:
# Vamos criar um array de strings
array6 = np.array(['manipulacao','de','dados'])
array6

array(['manipulacao', 'de', 'dados'], dtype='<U11')

In [18]:
# Tipo U11 e basicamente o tipo unicode ou seja tipo string para simplificar
# Porem o numpy trata internamente como unicode
# Unicode e uma forma de codificacao strings
# No python seria o tipo string mas no numpy isso muda
# Uma enumeracao especifica que representa as strings
array6.dtype

dtype('<U11')

In [21]:
# Veja so, agora vamos incluir palavras sem as aspas
# Isso pq essas palavras nao sao strings comuns
# Essas palavras sao especificas na programacao
# Elas na verdade sao valores booleanos
# Se colocarmos aspas essas palavras se tornam simples Unicodes
array7 = np.array([True,False,True]);array7

array([ True, False,  True])

In [20]:
array7.dtype

dtype('bool')

In [22]:
# Agora vamos criar outro array
# Com valor inteiro, negativo e decimal
array8 = np.array([15,-1,7.99])

In [23]:
array8.dtype

dtype('float64')

In [24]:
# Caso queiramos mudar o tipo de dados do array
# Ao fazer arredondamento perceba que vc perde parte do dado, 0.99 neste caso
# Isso pode fazer muita diferenca
array8.astype(int)

array([15, -1,  7])

In [25]:
# Caso vc queira arredondar
# Perceba que primeiro precisamos arredondar o array
# Apenas depois que conseguimos claro converter para numero inteiro
print(np.round(array8).astype(int))

[15 -1  8]
