### Manipulacao de Dados com Numpy

#### Aula 14 – Reshaping e Ordenacao de Arrays

In [1]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [2]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 14 – Reshaping e Ordenacao de Arrays

In [3]:
# Vamos comecar criando um array simples com arange
array1 = np.arange(1,11) ; array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Veja o shape
array1.shape

(10,)

### Reshaping

In [7]:
# Vamos mudar o shape deste array
# Queremos agora fazer 2 linhas de 5 elementos
# Perceba a mudanca
array1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
array1.reshape(2,5).shape

(2, 5)

### Sort

In [9]:
# Vamos criar um array desordenado
array2 = np.array([[2,1],[15,-3]])
array2

array([[ 2,  1],
       [15, -3]])

In [10]:
# Vamos ordenar o array em nivel de linha
# axis = 0 coluna
# axis = 1 linha
# No array2 original veja que era  2,1 e 15,-3
# Ele foi ordenado de forma crescente em nivel de linha
array2.sort(axis = 1)
array2

array([[ 1,  2],
       [-3, 15]])

In [12]:
# Vamos ordenar o array em nivel de coluna
# Nivel de coluna o axis = 0
# Veja que as colunas eram 2,15 e 1,-3
# As colunas foram ordenadas de forma crescente
# Veja que os elementos mudaram de lugar por causa da ordenacao por coluna
array2.sort(axis = 0)
array2

array([[-3,  2],
       [ 1, 15]])

#### Entao com esta aula nos terminamos o primeiro capitulo do curso, veja que aprendemos varias funcionalidades do NumPy muito importantes para vc utilizar no seu dia a dia, agora nos vamos aplicar estes conceitos na pratica.

#### Vamos usar um dataset publico cheio de problemas que precisam ser corrigidos, e vamos entao fazer uma serie de transformacoes usando NumPy e de quebra montar um portfolio profissional para vc adicionar ao seu curriculo.

#### Voce esta preparado ? Vamos nessa !