### Manipulacao de Dados com Numpy

#### Aula 13 – Operadores Logicos

In [4]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [5]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 13 – Operadores Logicos

##### Operador Logico e aquele que retorna como resultado True ou False lembram.

##### == Igualdade
##### != Diferenca
##### >= Maior ou igual
##### <= Menor ou igual
##### > Maior
##### < Menor

##### Fazemos uma relacao logica e entao ele retorna se e True ou False

In [6]:
# Vamos criar um array com a funcao randint
# Ou seja ele vai criar uma matriz 4 por 4 (size)
# Essa matriz vai ser feita de numeros aleatorios de 1 a 10 sendo 10 exclusive
# Caso vc queira produzir o mesmo resultado aleatorio que eu use o np.random.seed()
# Ele faz vc ter o mesmo resultado aleatorio que eu
np.random.seed(10)

array1 = np.random.randint(1,10, size = (4,4))
array1

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1],
       [5, 7, 9, 2]])

#### any

In [9]:
# Vamos chamar o metodo any
# Veja o que estamos fazendo
# Numpy se por acaso eu dividir o array1 por 7
# Ou seja, se cada elemento do array1 for dividido por 7
# EU vou ter algum resultado com resto de divisao = 0 ?
# o % em python significa --resultado da divisao-- e um modulo em python

# True pq, pq o any vai verificar se --qualquer-- elemento do array
# tem ou nao resto de divisao por 7
# se pelo menos 1 elemento tiver resto de divisao == 0 ele retorna True
# Se nao ele retornara False
# Mude o Seed para 100 e veja o resultado mudar pois nao havera numero divisivel no array

np.any((array1 % 7) == 0)

True

#### all

In [10]:
# Agora queremos saber se TODOS os elementos 
# Do array tem resto de divisao por 7 == 0, veja que nao claro

np.all((array1 % 7) == 0)

False

In [11]:
# Agora todos os elementos sao menores que 20
# Nos criamos um array de numeros aleatores inteiros de 1 ate 10 lembra
# Ou seja, True
np.all((array1 < 20))

True

#### Mas e se alem de verificar quisermos saber qual e o elemento True ? para isso usamos outra funcao

### where

In [14]:
# Veja, queremos o indice do elemento do array 
# Da coluna de indice 2
# Onde este elemento seja maior que 3 E menor que 8
# Ele disse que e o elemento de indice 2
# Ou seja e o numero 4
np.where(np.logical_and(array1[:,2] > 3, array1[:,2] < 8))

(array([2], dtype=int64),)

In [15]:
# Veja coluna de indice 2 inteira (2,1,4,9)
# E a linha indice 2 ( numero 4)
np.random.seed(10)

array1 = np.random.randint(1,10, size = (4,4))
array1

# Perceba que as possibilidades de filtragem vao ficando mais inteligentes
# Podemos fazer qualquer tipo de filtragem que vc conseguir imaginar

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1],
       [5, 7, 9, 2]])

### intersect1d

In [16]:
# Podemos fazer o mesmo tipo de busca que a anterior so que utilizando intersect1d
# E o where em vez do logical_and
# Veja que a funcao muda um pouco mas a saida e a mesma
np.intersect1d(np.where(array1[:,2] > 3), np.where(array1[:,2] < 8))

array([2], dtype=int64)