### Manipulacao de Dados com Numpy

#### Aula 6 – Operacoes com arrays !

In [1]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [2]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.22.3


### Aula 6 - Operacoes com Arrays

##### Perceba que ate agora nos criamos uma serie de arrays com diferentes tipos de dados, agora vamos aumentando o nivel aos poucos, vamos fazer operacoes com esses arrays algo muito comum no dia a dia de um programador

##### Multiplicacao

In [3]:
# Vamos começar criando um array comum usando arange

array1 = np.arange(0,20);array1

## Existem duas formas de criar este array usando operacoes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
# Perceba que cada elemento do array foi multiplicados por 5
# Porém o array se mantem como contagem de 0 a 19, claro
# Pois o objeto criado foi um array de 0 a 19
# Tudo isso com uma unica expressao simples
array1*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
# Agora vamos colocar esta operacao de multiplicacao dentro do objeto
array2 = np.arange(0,20)*5
array2
# Perceba que o array agora e essa contagem de 0 a 19
# Onde todos os valores estao sendo multiplicados por 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

##### Potencia

In [9]:
# Vamos elevar todos os numeros do array ao quadrado
# No Python apenas 1 aasterisco (*) e multiplicacao
# 2 asteriscos (**) e potencia em python
array3 = np.arange(0,20)**2;array3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

##### Soma

In [10]:
array4 = np.arange(0,20) + 10;array4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [11]:
# Vamos criar um array de 0 a 19 e adicinar +10 em cada elemento do array
# Vamos criar 2 arrays iguais para partirmos para proxima parte
array5 = np.arange(0,20,2) + 10
array6 = np.arange(0,20,2) + 10;array6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### Operacoes entre arrays

In [12]:
# Soma
# Perceba que os 2 arrays tem o mesmo tamanho
# E cada elemento do array5 somou ao elemento do array6 do indice correspondente
# Ou seja o 1º elemento do array5 somou com o 1º elemento do array6
# 2º com 2º etc
array5 + array6

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [13]:
# Subtracao
array5 - array6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Multiplicacao
array5 * array6

array([100, 144, 196, 256, 324, 400, 484, 576, 676, 784])

In [15]:
# Divisao
array5 / array6

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Comparacao entre arrays

In [18]:
array5 > array6

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
# Nao esqueca
# apenas um sinal de igual (=) vc esta fazendo atribuicao
# Para fazer comparacao vc deve usar dois sinais de igual (==)
# E diferenca nos usamos o !=
array5 == array6

In [19]:
# Booleanos
array7 = np.array([False, True, False, True])
array8 = np.array([False, False, True, True])


In [20]:
# Vamos usar uma funcao do numpy 
# para fazer comparacao logica booleana entre os elementos do array
np.logical_and(array7,array8)

# Veja false + false = false, true + true = true, false + true = false
# Isso e logica computacional
# Quase tudo feito no computador e no seu dia a dia depende da logica computacional

array([False, False, False,  True])

#### Nos poderiamos criar arrays com o python puro normal sem usar o NumPy. Porem o NumPy e muito mais performatico para fazer estas mesmas operacoes, veja uma comparacao.

In [21]:
# Veja o tempo estimado em microsegundos aquele us = microsegundos
# Isso para fazer as mesmas operacoes, isso pq o numpy e para computacao cientifica
# Por isso ele e feito para ser mais performatico mesmo
# Dependendo do seu volume de dados, essa diferenca e um divisor de aguas
# Para grandes modelos de redes neurais, IA, machine learning
# O numpy e muito usado devido a sua performance muito boa
array_numpy = np.arange(500)
%timeit array_numpy ** 4

2.07 µs ± 7.27 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
# Perceba a diferenca ate em como a operacao e feita
# Com python puro nos precisamos criar uma list comprehension
# E entao fazer um loop entre os elementos do array
# Veja para cada elemento i do array_python
# Nos vamos elevar o elemento i do array_python para 4 potencia
array_python = range(500)
%timeit [array_python[i] ** 4 for i in array_python]

146 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


##### Percebeu a diferenca GRITANTE